version: '3.9'
services:
  dev:
    container_name: heavy-compute-nest
    image: server-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile.dev
    command: npm run start:debug
    ports:
      - 3000:3000
    networks:
      - server-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  server-network: