apiVersion: skaffold/v2beta22
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: exsanik/nest-api
      context: .
      docker:
        dockerfile: ./Dockerfile.dev
      sync:
        infer: ["**/*.js", "**/*.ts", "**/*.html", "**/*.css"]
deploy:
  kubectl:
    manifests:
      - k8s/nest.deployment.yml
      - k8s/nest.node-port.yml