apiVersion: v1
kind: Service
metadata:
  name: nest-node-port
  namespace: nest
spec:
  type: NodePort
  selector:
    component: web
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31515