apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nest-deployment
  namespace: nest
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nest-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
